# Generated by Django 4.1.5 on 2023-01-16 05:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=11, null=True, region=None, unique=True, verbose_name='電話番号'),
        ),
    ]
