# Generated by Django 4.1.5 on 2023-01-16 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0002_alter_store_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='tel',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='電話番号'),
        ),
    ]
