# Generated by Django 4.1.5 on 2023-01-18 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0005_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='remarks',
        ),
    ]
