# Generated by Django 4.1.5 on 2023-01-18 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0006_remove_booking_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tel',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='電話番号'),
        ),
    ]
