# Generated by Django 4.1.5 on 2023-01-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0007_alter_booking_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='remarks',
            field=models.TextField(blank=True, default='', verbose_name='備考'),
        ),
    ]
