# Generated by Django 4.1.5 on 2023-01-19 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0008_booking_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='remarks',
        ),
    ]
