# Generated by Django 4.1.5 on 2023-01-26 01:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0010_defaultvalue_maxnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adlutnum',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='大人予約数'),
        ),
        migrations.AddField(
            model_name='booking',
            name='childnum',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='子供予約数'),
        ),
    ]
