# Generated by Django 4.1.5 on 2023-01-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0011_booking_adlutnum_booking_childnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultvalue',
            name='defaultvalue',
            field=models.IntegerField(blank=True, verbose_name='全日予約数'),
        ),
    ]
